name: deploy

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["18.14.2"]

    services:
      mongodb:
        image: mongo
        #So, by default, they assign the MongoDB instance to Mongo's default port of 27 0 1 7.
        ports:
          - 27017:27017
      redis:
        image: redis
        # defoult redis server port
        ports:
          - 6379:6379

    # აი ეს  დააყენებს  ci ს დროს port ს 3000 ზე
    env:
      NODE_ENV: ci
      PORT: 3000

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies

        run: |
          npm install --legacy-peer-deps
          npm run build

      - name: Start server

        run: |
          nohup npm run start &
          sleep 3
      - name: Run tests
        run: npm run test
